// Mix table: every sound's target loudness + polyphony / rate-limit / pitch-variation / ducking rules. Hand-tuned; measured file levels come from
// src/core/mixLevels.js (generated by tools/measure_audio.py), so all variants of a key (shoot, shoot_2, shoot_3) play equally loud and the
// manifest "volume" is only a fallback for keys without a row.
//
//   db     target loudness in dB (gated RMS, before master/user volume). ~-20 = punchy/important, -28 = frequent gunfire, -40 = barely there.
//   poly   max simultaneous voices of this key (or of `group`); the OLDEST voice is cut with a short fade when the cap is hit.
//   gap    min seconds between two plays of the same key (rate limit).  rand: random detune range in cents (only when caller passes no detune).
//   duck   [musicLevel, holdSeconds]: important stingers dip the music (and ambience) so they cut through, then it swells back.
//   chain  pickups that rise in pitch when collected in quick succession (coins).
// Adding a sound: add a row (or nothing: unknown keys get DEFAULT_DB, group 'creature' for the animal/undead calls).
import { LEVELS } from './mixLevels.js';

export const DEFAULT_DB = -27;
const CREATURE = ['coyote_howl', 'snake_rattle', 'snake_hiss', 'buzzard_screech', 'ghost_wail', 'crow_caw', 'bat_screech', 'skeleton_rattle', 'zombie_groan', 'dig', 'coffin_open', 'lasso_swish', 'whip_crack'];

export const MIX = {
  // --- player weapon (fatigue control: quiet, capped, pitch-varied) ---
  shoot: { db: -28, poly: 5, group: 'shot', gap: 0.035, rand: 110 },
  shoot_crit: { db: -21, poly: 2, group: 'shot_crit', gap: 0.06, rand: 60 },
  gun_cock: { db: -29, poly: 2, gap: 0.08, rand: 60 },
  sixth_bullet_ready: { db: -25, poly: 1, gap: 0.1 },
  dodge_roll: { db: -31, poly: 2, gap: 0.1, rand: 120 },
  // --- impacts ---
  enemy_hit: { db: -31, poly: 4, gap: 0.05, rand: 160 },
  bullet_hit_wall: { db: -37, poly: 3, gap: 0.05, rand: 200 },
  boss_hit: { db: -27, poly: 3, gap: 0.08, rand: 100 },
  enemy_die: { db: -27, poly: 3, gap: 0.06, rand: 150 },
  boss_die: { db: -19, poly: 1, gap: 0.5, duck: [0.3, 3.2] },
  explosion: { db: -21, poly: 3, gap: 0.05, rand: 140 },
  // --- important (must cut through) ---
  player_hurt: { db: -19, poly: 1, gap: 0.12, rand: 60, duck: [0.55, 0.5] },
  player_die: { db: -19, poly: 1, gap: 0.5 }, // no duck: the death stinger must be heard
  item_get: { db: -22, poly: 1, gap: 0.3, duck: [0.45, 2.2] },
  room_clear: { db: -24, poly: 1, gap: 0.5, duck: [0.55, 2.0] },
  boss_intro: { db: -20, poly: 1, gap: 0.5, duck: [0.3, 3.4] },
  shop_buy: { db: -24, poly: 2, gap: 0.1 },
  shop_deny: { db: -26, poly: 1, gap: 0.3 },
  // --- pickups / world ---
  pickup_coin: { db: -29, poly: 3, gap: 0.045, chain: true },
  pickup_heart: { db: -24, poly: 2, gap: 0.15 },
  pickup_key: { db: -24, poly: 2, gap: 0.15 },
  pickup_dynamite: { db: -25, poly: 2, gap: 0.15 },
  door_open: { db: -28, poly: 2, gap: 0.15, rand: 80 },
  door_close: { db: -27, poly: 2, gap: 0.15, rand: 80 },
  door_locked: { db: -28, poly: 1, gap: 0.4 },
  door_unlock: { db: -26, poly: 2, gap: 0.15 },
  trapdoor: { db: -24, poly: 1, gap: 0.5 },
  spawn: { db: -31, poly: 3, gap: 0.12, rand: 250 },
  fuse: { db: -35, poly: 4, gap: 0.3 },
  heartbeat: { db: -25 },
  step_dirt: { db: -40, poly: 2, gap: 0.12, rand: 250 },
  step_wood: { db: -38, poly: 2, gap: 0.12, rand: 250 },
  // --- ui ---
  menu_move: { db: -30, poly: 2, gap: 0.04 },
  menu_select: { db: -26, poly: 2, gap: 0.05 },
  pause: { db: -27, poly: 1, gap: 0.2 },
  // --- looped beds ---
  amb_wind: { db: -41 },
  amb_cave: { db: -39 },
  mus_menu: { db: -30 }, mus_floor1: { db: -30 }, mus_floor2: { db: -30.5 }, mus_floor3: { db: -30.5 },
  mus_boss: { db: -28 }, mus_boss_final: { db: -27.5 }, mus_shop: { db: -33 },
  mus_death: { db: -27 }, mus_victory: { db: -27 },
};
for (const k of CREATURE) MIX[k] = { db: -27, poly: 4, group: 'creature', gap: 0.08, rand: 100, ...(MIX[k] || {}) };

/** Music that is streamed on demand (see AudioLoader). Everything else - all SFX - loads up front. Death/victory stingers are tiny -> eager. */
const EAGER = new Set(['mus_death', 'mus_victory']);
export const isLazyAudio = (key, meta) => ((meta && meta.type === 'music') || key.startsWith('amb_')) && !EAGER.has(key);

const dbToLin = (d) => Math.pow(10, d / 20);

/** Linear gain for a concrete file variant so that it lands on the key's target loudness (clamped: never > +6 dB boost, never past 0 dBFS). */
export function gainFor(baseKey, file, fallbackVol = 0.6) {
  const row = MIX[baseKey];
  const lv = LEVELS[file];
  if (!lv) return fallbackVol; // unknown file -> manifest volume
  const target = row ? row.db : DEFAULT_DB;
  let g = target - lv[0];
  g = Math.min(g, 6, -0.5 - lv[1]);
  return dbToLin(g);
}
/** Mix row for a key incl. variants ('shoot_2' -> 'shoot'). */
export function rowFor(key) {
  return MIX[key] || MIX[key.replace(/_\d+$/, '')] || null;
}
