// Mix table: every sound's target loudness + polyphony / rate-limit / pitch-variation / ducking rules. Hand-tuned; measured file levels come from
// src/core/mixLevels.js (generated by tools/measure_audio.py), so all variants of a key (shoot, shoot_2, shoot_3) play equally loud and the
// manifest "volume" is only a fallback for keys without a row.
//
//   db     target loudness in dB (gated RMS, before master/user volume). ~-20 = punchy/important, -28 = frequent gunfire, -40 = barely there.
//   poly   max simultaneous voices of this key (or of `group`); the OLDEST voice is cut with a short fade when the cap is hit.
//   gap    min seconds between two plays of the same key (rate limit).  rand: random detune range in cents (only when caller passes no detune).
//   duck   [musicLevel, holdSeconds]: important stingers dip the music (and ambience) so they cut through, then it swells back.
//   chain  pickups that rise in pitch when collected in quick succession (coins).
// Adding a sound: add a row (or nothing: unknown keys get DEFAULT_DB, group 'creature' for the animal/undead calls).
import { LEVELS } from './mixLevels.js';

export const DEFAULT_DB = -27;
const CREATURE = ['coyote_howl', 'snake_rattle', 'snake_hiss', 'buzzard_screech', 'ghost_wail', 'crow_caw', 'bat_screech', 'skeleton_rattle', 'zombie_groan', 'dig', 'coffin_open', 'lasso_swish', 'whip_crack',
  'hound_growl', 'bull_snort', 'rat_squeak', 'mimic_chomp', 'blood_moon_howl'];

export const MIX = {
  // --- player weapon (fatigue control: quiet, capped, pitch-varied) ---
  shoot: { db: -28, poly: 5, group: 'shot', gap: 0.035, rand: 110 },
  shoot_crit: { db: -21, poly: 2, group: 'shot_crit', gap: 0.06, rand: 60 },
  gun_cock: { db: -29, poly: 2, gap: 0.08, rand: 60 },
  sixth_bullet_ready: { db: -25, poly: 1, gap: 0.1 },
  dodge_roll: { db: -31, poly: 2, gap: 0.1, rand: 120 },
  // --- impacts ---
  enemy_hit: { db: -31, poly: 4, gap: 0.05, rand: 160 },
  bullet_hit_wall: { db: -37, poly: 3, gap: 0.05, rand: 200 },
  boss_hit: { db: -27, poly: 3, gap: 0.08, rand: 100 },
  enemy_die: { db: -27, poly: 3, gap: 0.06, rand: 150 },
  boss_die: { db: -19, poly: 1, gap: 0.5, duck: [0.3, 3.2] },
  explosion: { db: -21, poly: 3, gap: 0.05, rand: 140 },
  // --- important (must cut through) ---
  player_hurt: { db: -19, poly: 1, gap: 0.12, rand: 60, duck: [0.55, 0.5] },
  player_die: { db: -19, poly: 1, gap: 0.5 }, // no duck: the death stinger must be heard
  item_get: { db: -22, poly: 1, gap: 0.3, duck: [0.45, 2.2] },
  room_clear: { db: -24, poly: 1, gap: 0.5, duck: [0.55, 2.0] },
  boss_intro: { db: -20, poly: 1, gap: 0.5, duck: [0.3, 3.4] },
  shop_buy: { db: -24, poly: 2, gap: 0.1 },
  shop_deny: { db: -26, poly: 1, gap: 0.3 },
  // --- pickups / world ---
  pickup_coin: { db: -29, poly: 3, gap: 0.045, chain: true },
  pickup_heart: { db: -24, poly: 2, gap: 0.15 },
  pickup_key: { db: -24, poly: 2, gap: 0.15 },
  pickup_dynamite: { db: -25, poly: 2, gap: 0.15 },
  door_open: { db: -28, poly: 2, gap: 0.15, rand: 80 },
  door_close: { db: -27, poly: 2, gap: 0.15, rand: 80 },
  door_locked: { db: -28, poly: 1, gap: 0.4 },
  door_unlock: { db: -26, poly: 2, gap: 0.15 },
  trapdoor: { db: -24, poly: 1, gap: 0.5 },
  spawn: { db: -31, poly: 3, gap: 0.12, rand: 250 },
  fuse: { db: -35, poly: 4, gap: 0.3 },
  heartbeat: { db: -25 },
  step_dirt: { db: -40, poly: 2, gap: 0.12, rand: 250 },
  step_wood: { db: -38, poly: 2, gap: 0.12, rand: 250 },
  // --- ui ---
  menu_move: { db: -30, poly: 2, gap: 0.04 },
  menu_select: { db: -26, poly: 2, gap: 0.05 },
  pause: { db: -27, poly: 1, gap: 0.2 },
  // --- looped beds ---
  amb_wind: { db: -41 },
  amb_cave: { db: -39 },
  amb_lava: { db: -40 }, amb_rail: { db: -40 }, amb_saloon: { db: -41 }, amb_crossroads: { db: -41 },
  mus_menu: { db: -30 }, mus_floor1: { db: -30 }, mus_floor2: { db: -30.5 }, mus_floor3: { db: -30.5 },
  mus_boss: { db: -28 }, mus_boss_final: { db: -27.5 }, mus_shop: { db: -33 },
  mus_death: { db: -27 }, mus_victory: { db: -27 },
  // round 2 music (AUDIO_SPEC_V2 s2 / s5)
  mus_floor4: { db: -30.5 }, mus_floor5: { db: -30.5 }, mus_floor6: { db: -30.5 },
  mus_boss4: { db: -28 }, mus_boss5_a: { db: -28 }, mus_boss5_b: { db: -27.8 }, mus_boss5_c: { db: -27.5 },
  mus_boss6_a: { db: -28 }, mus_boss6_b: { db: -27.8 }, mus_boss6_c: { db: -27.5 }, mus_boss6_d: { db: -30 },
  mus_interlude: { db: -31 }, mus_crossroads: { db: -32 }, mus_miniboss: { db: -29 }, mus_cutscene_intro: { db: -31 },
  mus_ending_a: { db: -30 }, mus_ending_true: { db: -30 }, mus_credits: { db: -31 },

  // --- round 2, chapter 2 world (AUDIO_SPEC_V2 s4.1): db, poly, gap, rand; duck = important stingers ---
  lava_bubble: { db: -32, poly: 2, gap: 0.3, rand: 150 },
  lava_burst: { db: -26, poly: 2, gap: 0.2 },
  vent_hiss: { db: -32, poly: 3, gap: 0.3 },
  vent_erupt: { db: -24, poly: 2, gap: 0.3, rand: 100 },
  fire_whoosh: { db: -27, poly: 3, gap: 0.1, rand: 150 },
  fire_crackle: { db: -38, poly: 2 }, fire_loop: { db: -38, poly: 2 }, // looped by Sfx.loop: one shared loop while any patch lives
  bull_roar: { db: -20, poly: 1, gap: 0.5, duck: [0.45, 1.2] },
  hoof_thunder: { db: -25, poly: 1, gap: 0.5 },
  train_horn: { db: -20, poly: 1, gap: 0.5, duck: [0.45, 1.5] },
  train_bell: { db: -27, poly: 4, gap: 0.15 },
  rail_clatter: { db: -30, poly: 2, gap: 0.2 },
  cart_rumble: { db: -28, poly: 2, gap: 0.3 },
  steam_hiss: { db: -31, poly: 3, gap: 0.3 },
  steam_blast: { db: -24, poly: 2, gap: 0.3 },
  coal_thud: { db: -30, poly: 3, gap: 0.08, rand: 200 },
  chain_rattle: { db: -30, poly: 2, gap: 0.3 },
  card_throw: { db: -30, poly: 4, gap: 0.06, rand: 200 },
  card_shuffle: { db: -29, poly: 1, gap: 0.4 },
  chip_clatter: { db: -31, poly: 3, gap: 0.1 },
  dice_roll: { db: -29, poly: 2, gap: 0.2 },
  slot_spin: { db: -32, poly: 1, gap: 0.5 },
  slot_ding: { db: -27, poly: 1, gap: 0.3 },
  slot_jam: { db: -26, poly: 1, gap: 0.4 },
  glass_break: { db: -27, poly: 3, gap: 0.08, rand: 150 },
  chandelier_creak: { db: -27, poly: 1, gap: 1.0 },
  chandelier_crash: { db: -20, poly: 1, gap: 1.0, duck: [0.5, 0.8] },
  roulette_tick: { db: -31, poly: 2, gap: 0.2 },
  roulette_zap: { db: -27, poly: 2, gap: 0.2 },
  piano_sting: { db: -26, poly: 1, gap: 0.5 },
  devil_laugh: { db: -20, poly: 1, gap: 0.5, duck: [0.4, 1.5] },
  contract_tear: { db: -22, poly: 1, gap: 0.5, duck: [0.4, 1.5] },
  seal_break: { db: -27, poly: 3, gap: 0.1 },
  // --- crossroads (s4.2)
  hellgate_open: { db: -21, poly: 1, gap: 0.5, duck: [0.5, 1.5] },
  hellgate_enter: { db: -25, poly: 1, gap: 0.5 },
  dealer_laugh: { db: -23, poly: 1, gap: 0.5 },
  dealer_mumble: { db: -34, poly: 2, gap: 0.05, rand: 300 },
  contract_hover: { db: -33, poly: 1, gap: 0.15 },
  contract_sign: { db: -22, poly: 1, gap: 0.5, duck: [0.5, 1.2] },
  heart_pay: { db: -23, poly: 1, gap: 0.3 },
  curse_gain: { db: -24, poly: 1, gap: 0.3 },
  blessing_gain: { db: -25, poly: 1, gap: 0.3 },
  revive_ace: { db: -19, poly: 1, gap: 1.0, duck: [0.35, 2.0] },
  // --- events, minis, elites, hazards, modifiers (s4.3)
  card_flip: { db: -30, poly: 3, gap: 0.08, rand: 100 },
  card_win: { db: -27, poly: 1, gap: 0.3 },
  card_lose: { db: -27, poly: 1, gap: 0.3 },
  chip_place: { db: -32, poly: 3, gap: 0.08, rand: 150 },
  well_plink: { db: -31, poly: 2, gap: 0.1, rand: 200 },
  well_wish: { db: -26, poly: 1, gap: 0.3 },
  shovel_dig: { db: -29, poly: 2, gap: 0.12, rand: 150 },
  grave_crack: { db: -27, poly: 1, gap: 0.3 },
  grave_open: { db: -26, poly: 1, gap: 0.3 },
  bottle_pop: { db: -29, poly: 1, gap: 0.2, rand: 100 },
  potion_gulp: { db: -29, poly: 1, gap: 0.3, rand: 100 },
  bell_toll: { db: -24, poly: 2, gap: 0.3 },
  duel_start: { db: -24, poly: 1, gap: 0.5 },
  duel_draw: { db: -20, poly: 1, gap: 0.3, duck: [0.35, 1.0] },
  quick_draw_ding: { db: -27, poly: 1, gap: 0.3 },
  mini_intro: { db: -20, poly: 1, gap: 0.5, duck: [0.35, 2.0] },
  chain_whirl: { db: -29, poly: 2, gap: 0.25 },
  rock_crumble: { db: -30, poly: 3, gap: 0.1, rand: 200 },
  censer_swing: { db: -30, poly: 2, gap: 0.25 },
  elite_spawn: { db: -26, poly: 2, gap: 0.3 },
  elite_ting: { db: -30, poly: 3, gap: 0.08, rand: 150 },
  elite_pop: { db: -30, poly: 3, gap: 0.15 },
  quicksand_bubble: { db: -34, poly: 2, gap: 0.3, rand: 150 },
  spikes_ret: { db: -30, poly: 2, gap: 0.2 },
  rock_warn: { db: -32, poly: 2, gap: 0.3 },
  rock_impact: { db: -27, poly: 2, gap: 0.2, rand: 150 },
  lurch_creak: { db: -32, poly: 1, gap: 0.5 },
  wall_knock: { db: -30, poly: 2, gap: 0.2 },
  stampede_rumble: { db: -25, poly: 1, gap: 0.5 },
  stampede_hoof: { db: -27, poly: 2, gap: 0.2 },
  secret_reveal: { db: -26, poly: 2, gap: 0.15 },
  // --- story / UI (s4.4)
  ui_type: { db: -38, poly: 2, gap: 0.05, rand: 200 },
  ink_splat: { db: -27, poly: 2, gap: 0.2 },
  page_flip: { db: -31, poly: 2, gap: 0.15, rand: 120 },
  pen_scratch: { db: -31, poly: 2, gap: 0.15, rand: 120 },
  clock_tick: { db: -34, poly: 1, gap: 0.3 },
  crowd_murmur: { db: -36, poly: 2 },
  wind_gust: { db: -33, poly: 2, gap: 0.5, rand: 200 },
  page_burn: { db: -29, poly: 1, gap: 0.3 },
  // --- items / meta / character polish (s4.5; optional, aliases exist)
  synergy_chime: { db: -24, poly: 1, gap: 0.3 },
  shock_zap: { db: -30, poly: 3, gap: 0.08, rand: 200 },
  freeze_shatter: { db: -30, poly: 2, gap: 0.1, rand: 150 },
  holy_chime: { db: -28, poly: 2, gap: 0.2 },
  mark_lock: { db: -30, poly: 1, gap: 0.2 },
  ricochet_ping: { db: -36, poly: 3, gap: 0.05, rand: 250 },
  stamp_slam: { db: -26, poly: 1, gap: 0.3 },
  shoot_scatter: { db: -26, poly: 5, group: 'shot', gap: 0.035, rand: 110 },
  shoot_rifle: { db: -26, poly: 5, group: 'shot', gap: 0.035, rand: 110 },
  shoot_twin: { db: -28, poly: 5, group: 'shot', gap: 0.035, rand: 110 },
  // --- unlisted keys the code calls (aliased): default level, sensible limits
  signal_lamp_on: { db: -29, poly: 1, gap: 0.3 },
  card_burn: { db: -30, poly: 1, gap: 0.3 },
  ember_warn: { db: -33, poly: 2, gap: 0.2, rand: 200 },
  curse: { db: -24, poly: 1, gap: 0.3 },
  // creature group members with their own level / limits (merged into the 'creature' group below)
  hound_growl: { db: -28, gap: 0.3, rand: 150 },
  bull_snort: { db: -26, gap: 0.4, rand: 100 },
  rat_squeak: { db: -33, gap: 0.08, rand: 250 },
  mimic_chomp: { db: -26, gap: 0.2 },
  blood_moon_howl: { db: -28, gap: 0.5 },
};
for (const k of CREATURE) MIX[k] = { db: -27, poly: 4, group: 'creature', gap: 0.08, rand: 100, ...(MIX[k] || {}) };

/** Music that is streamed on demand (see AudioLoader). Everything else - all SFX - loads up front. Death/victory stingers are tiny -> eager. */
const EAGER = new Set(['mus_death', 'mus_victory']);
export const isLazyAudio = (key, meta) => ((meta && meta.type === 'music') || key.startsWith('amb_')) && !EAGER.has(key);

const dbToLin = (d) => Math.pow(10, d / 20);

/** Linear gain for a concrete file variant so that it lands on the key's target loudness (clamped: never > +6 dB boost, never past 0 dBFS). */
export function gainFor(baseKey, file, fallbackVol = 0.6) {
  const row = MIX[baseKey];
  const lv = LEVELS[file];
  if (!lv) return fallbackVol; // unknown file -> manifest volume
  const target = row ? row.db : DEFAULT_DB;
  let g = target - lv[0];
  g = Math.min(g, 6, -0.5 - lv[1]);
  return dbToLin(g);
}
/** Mix row for a key incl. variants ('shoot_2' -> 'shoot'). */
export function rowFor(key) {
  return MIX[key] || MIX[key.replace(/_\d+$/, '')] || null;
}
