#!/usr/bin/env python3
"""Measure every audio file (ffmpeg decode -> numpy) and write src/core/mixLevels.js = {file: [gatedRmsDb, peakDb]} for the runtime mixer (src/core/mix.js).
Also prints warnings: silent / too quiet / clipping / loop-seam clicks / truncated durations. Run from project root after audio changes:
  .venv-art/bin/python tools/measure_audio.py
gatedRmsDb: RMS in dBFS over 20 ms frames that are within 30 dB of the loudest frame (ignores silent tails, so short & long sounds compare fairly).
"""
import glob, json, os, subprocess
import numpy as np

ROOT = 'public/assets/audio'
SR = 44100


def decode(p):
    r = subprocess.run(['ffmpeg', '-v', 'error', '-i', p, '-f', 'f32le', '-ac', '1', '-ar', str(SR), '-'], capture_output=True)
    return np.frombuffer(r.stdout, dtype=np.float32)


def db(x):
    return 20 * np.log10(max(float(x), 1e-9))


man = json.load(open('public/assets/manifest.json'))['audio']
loops = {v['file'] for v in man.values() if v.get('loop')}
levels, warn = {}, []
for p in sorted(glob.glob(f'{ROOT}/**/*.mp3', recursive=True) + glob.glob(f'{ROOT}/**/*.ogg', recursive=True)):
    rel = os.path.relpath(p, ROOT)
    x = decode(p)
    if len(x) < 64:
        warn.append(f'{rel}: EMPTY/undecodable')
        continue
    peak = float(np.abs(x).max())
    n = int(SR * 0.02)
    m = len(x) // n
    fr = np.sqrt((x[: m * n].reshape(m, n) ** 2).mean(axis=1) + 1e-12)
    gate = fr.max() * 10 ** (-30 / 20)
    act = fr[fr >= gate]
    rms = float(np.sqrt((act ** 2).mean()))
    levels[rel] = [round(db(rms), 1), round(db(peak), 1)]
    dur = len(x) / SR
    if peak < 0.02: warn.append(f'{rel}: nearly SILENT (peak {db(peak):.0f} dB)')
    elif db(rms) < -34: warn.append(f'{rel}: very quiet (gated rms {db(rms):.0f} dB) - mix.js will boost it')
    if peak >= 0.999 and not rel.startswith('music/'): warn.append(f'{rel}: CLIPS (peak {db(peak):.1f} dB)')
    if dur < 0.05: warn.append(f'{rel}: very short ({dur*1000:.0f} ms)')
    if rel in loops or any(rel.endswith(s) for s in ('heartbeat.mp3', 'fuse.mp3')):
        head, tail = x[:882], x[-882:]
        jump = abs(float(head[0]) - float(tail[-1]))
        rmsj = abs(db(np.sqrt((head ** 2).mean())) - db(np.sqrt((tail ** 2).mean())))
        if jump > 0.3 or rmsj > 18:
            warn.append(f'{rel}: loop seam may click (sample jump {jump:.2f}, edge rms diff {rmsj:.0f} dB)')

with open('src/core/mixLevels.js', 'w') as f:
    f.write('// GENERATED by tools/measure_audio.py - do not edit. {file (relative to audio/): [gated RMS dBFS, peak dBFS]}\n')
    f.write('export const LEVELS = ' + json.dumps(levels, separators=(',', ':'), sort_keys=True) + ';\n')
print(f'{len(levels)} files measured -> src/core/mixLevels.js')
for w in warn:
    print('WARN', w)
